### ISSUE TITLE
查询余票几百次后, 程序报错后退出

### ISSUE THREAD

**Issue by Anakinliu** [versionzhang/python_12306#21]
```
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Programs\Python\Python37\Scripts\py12306-script.py", line 11, in <module>
    load_entry_point('py12306==0.9.1', 'console_scripts', 'py12306')()
  File "c:\users\1\appdata\local\programs\python\python37\lib\site-packages\python12306\cmd.py", line 7, in main
    instance.run()
  File "c:\users\1\appdata\local\programs\python\python37\lib\site-packages\python12306\scheduler.py", line 208, in run
    data = DispatcherTool.run(query_params)
  File "c:\users\1\appdata\local\programs\python\python37\lib\site-packages\python12306\logic\query\dispatcher.py", line 92, in run
    data = q.filter()
  File "c:\users\1\appdata\local\programs\python\python37\lib\site-packages\python12306\logic\query\query.py", line 53, in filter
    data = self.run_query()
  File "c:\users\1\appdata\local\programs\python\python37\lib\site-packages\python12306\logic\query\query.py", line 36, in run_query
    return [TrainDetail(v.split('|')) for v in json_response['data']['result']] or []
KeyError: `'data'`
```

**Comment by versionzhang** [comment]
谢谢反馈,这里可能是请求查询接口返回数据出现异常未捕获,已经修改,可以重新试一下

**Comment by Anakinliu** [comment]
运行了一下午, 没有再次报错, 抢到了票, 谢谢
