### ISSUE TITLE
车站信号获取失败

### ISSUE THREAD

**Issue by ghost** [versionzhang/python_12306#22]
获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
			获取车站信息失败，重试获取中
Traceback (most recent call last):
  File "/usr/local/bin/py12306", line 11, in <module>
    load_entry_point('py12306==0.9.1', 'console_scripts', 'py12306')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/python12306/cmd.py", line 1, in <module>
    from python12306.scheduler import Schedule
  File "/usr/local/lib/python3.6/dist-packages/python12306/scheduler.py", line 8, in <module>
    from python12306.logic.query.dispatcher import DispatcherTool
  File "/usr/local/lib/python3.6/dist-packages/python12306/logic/query/dispatcher.py", line 7, in <module>
    from .query import Query
  File "/usr/local/lib/python3.6/dist-packages/python12306/logic/query/query.py", line 9, in <module>
    from python12306.pre_processing.cities import CityData
  File "/usr/local/lib/python3.6/dist-packages/python12306/pre_processing/cities.py", line 77, in <module>
    CityData = CityTool().get_final_data()
  File "/usr/local/lib/python3.6/dist-packages/python12306/pre_processing/cities.py", line 73, in get_final_data
    self.to_python()
  File "/usr/local/lib/python3.6/dist-packages/python12306/pre_processing/cities.py", line 45, in to_python
    data = self.raw_data
  File "/usr/local/lib/python3.6/dist-packages/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/python12306/pre_processing/cities.py", line 42, in raw_data
    raise ResponseError
python12306.comonexception.ResponseError

**Comment by versionzhang** [comment]
请检查一下是不是使用了全局的socks代理, 可以使用http代理试一下

**Comment by ghost** [comment]
是这个问题，多谢啦！
